on:
  push:
    branches:
    - main
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
        token: ${{ secrets.GIT_BOT_TOKEN }}

    - id: nextversion
      name: next release version
      uses: jenkins-x-plugins/jx-release-version@v2.4.7
      env:
        TAG: "true"
        GIT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        GIT_EMAIL: jenkins-x@googlegroups.com
        GIT_NAME: jenkins-x-bot

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jenkins-x
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/jenkins-x/cosign:v0.3.1-${{ steps.nextversion.outputs.version }}
